### ISSUE TITLE
希望能改进一个功能

### ISSUE THREAD

**Issue by EdwinShadow** [zhou-you/EasySignSeekBar#3]
希望可以不显示节点但是可以有autot_section的功能，就是有节点但是不在进度条上显示出来

**Comment by zhou-you** [comment]
需求是无法完全满足的，特别是自定义的，千奇百怪。满足不了的只能自己进行修改。因为你这个功能不是大众很多人都需要的，即使修改了也是满足你一个人的，并不通用
